# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags: [ "v*" ]
    #branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    if: github.triggering_actor == 'nextdorf'
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      
      - name: Build python package
        run: |
          pip install --upgrade build
          python -m build
          PKGVERSION=$(python -c "$(grep version\ =\  matrixfuncs/_version.py); print(version)")
          echo "Build version $PKGVERSION"

      - name: LaTeX compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: matrix-functions-docu.tex
          # The working directory for the latex compiler to be invoked
          working_directory: tex
          # LaTeX engine to be used
          #compiler: # optional, default is latexmk
          # Extra arguments to be passed to the latex compiler
          #args: # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          # Install extra packages by apt-get
          #extra_system_packages: # optional

      - name: Upload documentation to releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          #automatic_release_tag: "${{ github.ref_name || 'nightly' }}"
          automatic_release_tag: "${PKGVERSION}"
          files: |
            tex/matrix-functions-docu.pdf
            dist/*
